/** Standardized notification event types */
export const EVENTS = {
  // Account
  USER_REGISTERED: "USER_REGISTERED",
  USER_APPROVED: "USER_APPROVED",
  USER_REJECTED: "USER_REJECTED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_REACTIVATED: "USER_REACTIVATED",

  // Security
  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  EMAIL_CHANGED: "EMAIL_CHANGED",
  SECURITY_ALERT: "SECURITY_ALERT",

  // Jobs
  JOB_CREATED: "JOB_CREATED",
  JOB_APPROVED: "JOB_APPROVED",
  JOB_REJECTED: "JOB_REJECTED",
  JOB_UPDATED: "JOB_UPDATED",

  // Applications
  APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
  APPLICATION_RECEIVED_EMPLOYER: "APPLICATION_RECEIVED_EMPLOYER",
  APPLICATION_REVIEWED: "APPLICATION_REVIEWED",
  APPLICATION_SHORTLISTED: "APPLICATION_SHORTLISTED",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",
  APPLICATION_SELECTED: "APPLICATION_SELECTED",
  APPLICATION_WITHDRAWN: "APPLICATION_WITHDRAWN",

  // Interviews
  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEW_RESCHEDULED: "INTERVIEW_RESCHEDULED",
  INTERVIEW_CANCELLED: "INTERVIEW_CANCELLED",
  INTERVIEW_REMINDER_24H: "INTERVIEW_REMINDER_24H",
  INTERVIEW_REMINDER_1H: "INTERVIEW_REMINDER_1H",
  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",

  // Resume
  RESUME_ANALYZED: "RESUME_ANALYZED",
  RESUME_TAILORED: "RESUME_TAILORED",
  RESUME_EXPORT_COMPLETED: "RESUME_EXPORT_COMPLETED",

  // Career
  JOB_RECOMMENDATIONS_READY: "JOB_RECOMMENDATIONS_READY",
  SKILL_GAP_DETECTED: "SKILL_GAP_DETECTED",
  JOB_DIGEST: "JOB_DIGEST",

  // Learning
  COURSE_ENROLLED: "COURSE_ENROLLED",
  COURSE_PROGRESS_MILESTONE: "COURSE_PROGRESS_MILESTONE",
  COURSE_COMPLETED: "COURSE_COMPLETED",
  COURSE_CERTIFICATE_READY: "COURSE_CERTIFICATE_READY",
  COURSE_RECOMMENDATIONS_READY: "COURSE_RECOMMENDATIONS_READY",

  // Recruiter
  RECRUITER_REGISTERED: "RECRUITER_REGISTERED",
};

/** Email template keys */
export const TEMPLATE_KEYS = {
  ACCOUNT_APPROVED: "ACCOUNT_APPROVED",
  ACCOUNT_REJECTED: "ACCOUNT_REJECTED",
  APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
  APPLICATION_SUBMITTED_EMPLOYER: "APPLICATION_SUBMITTED_EMPLOYER",
  APPLICATION_SHORTLISTED: "APPLICATION_SHORTLISTED",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",
  APPLICATION_SELECTED: "APPLICATION_SELECTED",
  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEW_RESCHEDULED: "INTERVIEW_RESCHEDULED",
  INTERVIEW_CANCELLED: "INTERVIEW_CANCELLED",
  INTERVIEW_REMINDER_24H: "INTERVIEW_REMINDER_24H",
  INTERVIEW_REMINDER_1H: "INTERVIEW_REMINDER_1H",
  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",
  JOB_APPROVED: "JOB_APPROVED",
  JOB_REJECTED: "JOB_REJECTED",
  JOB_CREATED_ADMIN: "JOB_CREATED_ADMIN",
  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  JOB_DIGEST: "JOB_DIGEST",
  RESUME_ANALYSIS_READY: "RESUME_ANALYSIS_READY",
  RECRUITER_REGISTERED: "RECRUITER_REGISTERED",
  USER_REGISTERED: "USER_REGISTERED",
};

export default EVENTS;
